### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by thomas-lamiaux** [Zimmi48/platform-docs#5]
We need to add a license for this project

**Comment by Zimmi48** [comment]
Yes, I would go with a permissive license, either CC-BY or even CC-0 (which is the license of the Coq wiki). However, we might need to accommodate other licenses for tutorials that are derivative of preexisting works.

**Comment by palmskog** [comment]
Please consider at least licensing code fragments under the [Unlicense](https://spdx.org/licenses/Unlicense.html) to allow people to easily copy code. Unlicense is also approved as an open source license, unlike CC0/CC-BY.

**Comment by Zimmi48** [comment]
(Comment written in parallel to Karl's above.)

As discussed in https://coq.zulipchat.com/#narrow/stream/437203-Coq-Platform-docs/topic/Licensing, it is important to make copy-pasting code from tutorials possible without hindrance. The logical thing then is to apply the Unlicense to all code snippets. What remains to be decided is whether to use the Unlicense for all the content of this repository (including the text of the tutorials), or to use the Unlicense for code snippets only and apply a different license (such as CC-BY) to the text of the tutorials.

We also need to decide if we accept tutorials that come with a different, preexisting license. My own view would be to accept them with their preexisting license if changing the license is too complicated.

cc all current contributors to the repo @thomas-lamiaux @Villetaneuse @CohenCyril @SkySkimmer @Vanille-N and potential future contributors @lephe. Let us know (explicitly) if you are fine with any option or if you have a preference.

**Comment by Vanille-N** [comment]
I believe that the text -- if any -- that I may have contributed that is still present in the document is exclusively code.
Regardless I am fine with everything coming from me being Unlicense'd, or any other you see fit.

**Comment by SkySkimmer** [comment]
Unlcense ok

**Comment by lephe** [comment]
I have a preference for Unlicense on code snippets and CC-BY for tutorial text, but I'll follow if Unlicense is chosen. Cc @YaZko

**Comment by Villetaneuse** [comment]
Like @lephe if it's not too complicated (Unlicense + CC-BY). I'm also ok with Unlicense for everything.

**Comment by Zimmi48** [comment]
Since it seems that the preference is for Unlicense + CC-BY, let's go with this license combination. I'll do a PR to apply this. As suggested by @lephe on Zulip, we will use a default "The Coq Platform Docs authors" for the paternity clause, although we should also look into how to preserve more fine-grained paternity when citing a tutorial academically (that's a different issue than the licensing though).

For the question of using a different license when importing preexisting material, we can decide when the situation arises.

@thomas-lamiaux 
> I believe we should be careful to that because on average the tuto and how-to should not be too long or so involve it requires a license to protect

I didn't manage to parse the end of your comment. But note that there is no clear rule on the minimum length a text must be to be copyrighted, but it is usually considered that it starts from very short texts (e.g., a Haiku is typically considered copyrightable, even though there is then a debate on whether you can quote the entire Haiku under fair use).

**Comment by palmskog** [comment]
@Zimmi48 one detail that worries me: will it always be clear what is a code snippet and what is text? That is, will all tutorials necessarily have this separation in some technical way? Otherwise, there could be borderline cases where it's unclear to the reader what is under CC-BY and what is under Unlicense.

**Comment by Zimmi48** [comment]
I think so, yes. The tutorials use a markup language (be it coqdoc or rst) which distinguishes between code blocks and text (the comments).
